name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs: 
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3
            
            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            # Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push the Docker image
            - name: Build and push Docker image
              run: | 
                docker buildx build --platform linux/amd64 --push -t faradzh/thescrumpoker:latest .
            
            # Deploy the Docker image on EC2
            - name: Deploy on EC2
              uses: appleboy/ssh-action@v1.2.1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                  docker pull faradzh/thescrumpoker:latest
                  docker stop $(docker ps -q) || true
                  docker rm $(docker ps -aq) || true
                  docker run --env-file .env -p 443:443 -v /etc/letsencrypt/archive/scrumspoker.com:/etc/letsencrypt/archive/scrumspoker.com/ faradzh/thescrumpoker